// AUTO-GENERATED — do not edit manually
// Run: node scripts/generate_audio.js
export const audioMap = {
  "Do you see something hiding all around you?": "/assets/audio/audio_do_you_see_something_hiding_all_around_y_0.mp3",
  "Look at your door. Look at your book. Look at your window. What shape do you notice?": "/assets/audio/audio_look_at_your_door_look_at_your_book_look_1.mp3",
  "There is a secret shape everywhere. Can you find it?": "/assets/audio/audio_there_is_a_secret_shape_everywhere_can_y_2.mp3",
  "Let us discover what this mystery shape is!": "/assets/audio/audio_let_us_discover_what_this_mystery_shape__3.mp3",
  "Look at a door. How many sides does it have?": "/assets/audio/audio_look_at_a_door_how_many_sides_does_it_ha_4.mp3",
  "Think of a book. What shape is it?": "/assets/audio/audio_think_of_a_book_what_shape_is_it__5.mp3",
  "A picture frame has a special shape. What is it?": "/assets/audio/audio_a_picture_frame_has_a_special_shape_what_6.mp3",
  "Look at a phone screen. How many corners can you count?": "/assets/audio/audio_look_at_a_phone_screen_how_many_corners__7.mp3",
  "Windows on a building — what shape are they?": "/assets/audio/audio_windows_on_a_building_what_shape_are_the_8.mp3",
  "Sarah and Mike were decorating their classroom for Art Day. There were picture frames, posters, and colourful charts everywhere!": "/assets/audio/audio_sarah_and_mike_were_decorating_their_cla_9.mp3",
  "Mike picked up a picture frame. \"How many sides does this have?\" asked their helper Robo. Mike traced his finger along the edges: one, two, three, four!": "/assets/audio/audio_mike_picked_up_a_picture_frame_how_many__10.mp3",
  "\"And how many corners?\" asked Robo. Sarah pointed at each corner of the frame. One, two, three, four! Four corners too!": "/assets/audio/audio__and_how_many_corners_asked_robo_sarah_p_11.mp3",
  "Robo pointed at the door. \"The door is the same shape! Four sides, four corners!\" Sarah looked around — the whiteboard, the window, even her notebook were the same shape!": "/assets/audio/audio_robo_pointed_at_the_door_the_door_is_the_12.mp3",
  "\"Here is the secret,\" said Robo. \"The sides across from each other are always the same length. The top matches the bottom, and the left matches the right!\"": "/assets/audio/audio__here_is_the_secret_said_robo_the_sides__13.mp3",
  "\"Now you know what a rectangle is!\" cheered Robo. \"Four sides, four corners, and opposite sides are always equal. Let us practice finding and making rectangles!\"": "/assets/audio/audio__now_you_know_what_a_rectangle_is_cheere_14.mp3",
  "4 sides!": "/assets/audio/audio_4_sides__15.mp3",
  "4 corners!": "/assets/audio/audio_4_corners__16.mp3",
  "Opposite sides are equal!": "/assets/audio/audio_opposite_sides_are_equal__17.mp3",
  "4 sides • 4 corners • Opposite sides equal": "/assets/audio/audio_4_sides_4_corners_opposite_sides_equal_18.mp3",
  "Tap four dots on the grid to make a rectangle!": "/assets/audio/audio_tap_four_dots_on_the_grid_to_make_a_rect_19.mp3",
  "Remember — a rectangle has 4 sides and 4 corners.": "/assets/audio/audio_remember_a_rectangle_has_4_sides_and_4_c_20.mp3",
  "Try to make the opposite sides equal!": "/assets/audio/audio_try_to_make_the_opposite_sides_equal__21.mp3",
  "Can you spot all the rectangles among these shapes?": "/assets/audio/audio_can_you_spot_all_the_rectangles_among_th_22.mp3",
  "Tap on each shape that is a rectangle!": "/assets/audio/audio_tap_on_each_shape_that_is_a_rectangle__23.mp3",
  "Great job finding the rectangles!": "/assets/audio/audio_great_job_finding_the_rectangles__24.mp3",
  "Let us test what you know about rectangles!": "/assets/audio/audio_let_us_test_what_you_know_about_rectangl_25.mp3",
  "Fill in the missing number.": "/assets/audio/audio_fill_in_the_missing_number__26.mp3",
  "You really know your rectangles!": "/assets/audio/audio_you_really_know_your_rectangles__27.mp3",
  "Amazing! That is correct!": "/assets/audio/audio_amazing_that_is_correct__28.mp3",
  "Hmm, let us look at that again!": "/assets/audio/audio_hmm_let_us_look_at_that_again__29.mp3",
  "Level complete! You are doing so well!": "/assets/audio/audio_level_complete_you_are_doing_so_well__30.mp3",
  "What a streak! You are on fire!": "/assets/audio/audio_what_a_streak_you_are_on_fire__31.mp3",
  "You found so many rectangles today!": "/assets/audio/audio_you_found_so_many_rectangles_today__32.mp3",
  "Can you teach Robo about rectangles? Answer these questions!": "/assets/audio/audio_can_you_teach_robo_about_rectangles_answ_33.mp3",
  "You are a Shape Hero today! Amazing work!": "/assets/audio/audio_you_are_a_shape_hero_today_amazing_work__34.mp3"
};
